apiVersion: v1
kind: Service
metadata:
  name: atm-locator
  namespace: finance
spec:
  selector:
    app: atm-locator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP